namespace WebApi.Common;

public enum GenreEnum
{
    ScienceFiction = 1,
    Fantasy,
    Horror,
    Romance,
    Thriller,
    Mystery,
    HistoricalFiction,
    Drama,
    ActionAndAdventure,
    SelfHelp,
    Health,
    Guide,
    Travel,
    Childrens,
    ReligionSpiritualityAndNewAge,
    Science,
    History,
    Math,
    Anthology,
    Poetry,
    Encyclopedias,
    Dictionaries,
    Comics,
    Art,
    Cookbooks,
    Diaries,
    Journals,
    PrayerBooks,
    Series,
    Trilogies,
    Biographies,
    Autobiographies
}